# Generated by Django 3.1.1 on 2020-09-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_doc', to='myapp.document'),
        ),
    ]
