# Generated by Django 3.1.1 on 2020-09-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_audio_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='document',
        ),
    ]
