# Generated by Django 3.1.1 on 2020-09-24 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200924_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='document_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_document_Audio', to='myapp.document'),
        ),
    ]
